#!/bin/bash
if [ -f /etc/arch-release ]; then 
    distro="arch" 
elif [ -f /etc/lsb-release ]; then 
    distro="ubuntu" 
else 
    echo "Unexpected distro"; exit 1 
fi

if [ "$distro" == "arch" ]; then
    ruby_version="2.0.0"
elif [ "$distro" == "ubuntu" ]; then
    ruby_version="1.8"
fi
PATH="$PATH:$HOME/.gem/ruby/$ruby_version/bin/"

. run-servers

if [[ -z $VIRTUAL_ENV ]]; then
    VIRTUAL_ENV="$HOME/.venv"
fi

$VIRTUAL_ENV/bin/python src/main_debug.py 127.0.0.1
