#!/bin/bash
if [ -f /etc/arch-release ]; then 
    distro="arch" 
elif [ -f /etc/lsb-release ]; then 
    distro="ubuntu" 
else 
    echo "Unexpected distro"; exit 1 
fi

if [ "$distro" == "arch" ]; then
#    if [ -z "`pidof mysqld`" ]; then
#        echo -n Mysql...
#        sudo systemctl start mysqld && echo started || echo failed
#    fi
    if [ -z "`pidof memcached`" ]; then
        echo -n Memcached...
        sudo systemctl start memcached && echo started || echo failed
    fi
    if [ -z "`pidof postgres`" ]; then
        echo -n Postgresql...
        sudo systemctl start postgresql && echo started || echo failed
    fi
fi
