#!/bin/bash

if [ "$distro" == "arch" ]; then
	if [ -z "`pidof mysqld`" ]; then
		sudo /etc/rc.d/mysqld start
	fi
fi
cd src
~/.venv/bin/gunicorn -w 4 -b 0.0.0.0:5000 --pythonpath src main_production 
#~/.venv/bin/python main_production.py
