#!/bin/bash

if [[ -z $VIRTUAL_ENV ]]; then
    VIRTUAL_ENV="$HOME/.venv"
fi

cd src
$VIRTUAL_ENV/bin/gunicorn -w 4 -b 0.0.0.0:5000 --pythonpath src main_production 
#$VIRTUAL_ENV/bin/python main_production.py
