#!/bin/bash
function confirm {
	local message="$1"
	if [[ -z "$all" ]]; then
		read -p "$message? [Y/n/a] " answer
		if [[ -z "$answer" || "$answer" =~ ^[yYaA] ]]; then
			if [[ "$answer" =~ ^[aA] ]]; then
				all=1
			fi
		else
			exit 1
		fi
	else
		echo "Executing $message..."
	fi
}

function require {
	local command="$1"
	local arch="$2"
	local ubuntu="$3"
	
	if [ "$distro" == "arch" ]; then
		local toinstall="$arch"
	elif [ "$distro" == "ubuntu" ]; then
		local toinstall="$ubuntu"
	fi
	type -P $command &>/dev/null || ls $command &>/dev/null || [ "$toinstall" == "" ] || {
		echo "$command missing" >&2
		confirm "$toinstall"
		$toinstall || exit 1
	}
}

function create_postgresql_user_and_db {
	local me=`whoami`
	psql -c '\qecho test'           >/dev/null 2>&1 || ( confirm "create user & db"    && sudo -i -u postgres createuser -s $me && sudo -i -u postgres createdb $me )
	psql -c '\qecho test' mysubtree >/dev/null 2>&1 || ( confirm "create db mysubtree" && sudo -i -u postgres createdb mysubtree )
	psql -c '\qecho test' test      >/dev/null 2>&1 || ( confirm "create db test"      && sudo -i -u postgres createdb test )
}
####################################################################

RUBY_PATH="$HOME/.local/share/gem/ruby/3.0.0/bin"
PATH="$PATH:$RUBY_PATH"

require pg_config     "sudo pacman -S postgresql"
require memcached     "sudo pacman -S memcached"

create_postgresql_user_and_db

require python-config "sudo pacman -S python"
require tidy          "sudo pacman -S tidyhtml"
require virtualenv    "sudo pacman -S python-virtualenv"
require npm           "sudo pacman -S nodejs"
require gem           "sudo pacman -S rubygems"
require /usr/include/libmemcached/memcached.h "sudo pacman -S libmemcached"
require $RUBY_PATH/compass "gem install compass"
require coffee        "sudo npm install -g coffee-script"
require uglifyjs      "sudo npm install -g uglify-js"

pushd src/mysubtree/backend/live/live_server
npm install
popd

pushd src/mysubtree/web/components/ext/famfamfam
./install.sh
popd

if [[ $VIRTUAL_ENV ]]; then
    pushd src
    python main_assetwatch.py
    popd
fi
