#!/bin/bash
. run-servers

clear

PYTHON="$VIRTUAL_ENV/bin/python"

if [[ -z $VIRTUAL_ENV ]]; then
    PYTHON="$HOME/.venv/bin/python"
fi

$PYTHON src/main_testing.py $@
#~/.venv/bin/coverage run --source=src/mysubtree src/main_testing.py $@
#~/.venv/bin/coverage html
