from datetime import datetime
from flask.ext.babel import gettext as _
from lib.error import Error
from mysubtree.db import db
from mysubtree.backend.live.live import on_node_insert
from mysubtree.web.user import get_user

class NodeAdding:
    def __init__(self):
        pass
    
    def is_addable_to_by_current_user(self):
        try:
            self._going_to_add()
        except Error:
            return False
        return True
    
    def add(self):
        self._going_to_add()
        self.validate()
        db.session.add(self)
        self.increment_counters()
        db.session.flush() # we need to save to db to know the autogenerated id but still inside uncommitted transaction
        on_node_insert(self)
    
    def _going_to_add(self):
        if not get_user():
            if self.type == "votes":
                pass # ok
            else:
                raise Error(_("You must be logged in to post anything."))